# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
permissions:
  contents: read

jobs:
  determine-matrix:
    runs-on: ubuntu-latest
    outputs:
      direcoties: ${{ steps.determine_matrix.outputs.directories }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: |
          import os
          import json
          from pathlib import Path
          tests_directory = Path('tests')
          immediate_directories = [str(x) for x in tests_directory.iterdir() if x.is_dir()]
          print(immediate_directories)
          with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
            fh.write(f'directories={json.dumps(immediate_directories)}')
        shell: python
        id: determine_matrix
  build:
    runs-on: ubuntu-latest
    needs: determine-matrix
    continue-on-error: true
    strategy:
      matrix:
        package: ${{ fromJSON(needs.determine-matrix.outputs.direcoties) }}
    steps:
    - uses: actions/checkout@v4
    - name: Package a lambda function
      uses: nickminaev/package-lambda-with-uv-action@main
      with:
        working-directory: ${{ matrix.package }}
      
